apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  selfLink: /apis/kafka.strimzi.io/v1beta1/namespaces/registry/kafkatopics/storage-topic
  resourceVersion: '694675'
  name: storage-topic
  uid: 2abd6985-fdff-4567-8063-2b05ee6df701
  creationTimestamp: '2020-10-02T09:34:34Z'
  generation: 1
  managedFields:
    - apiVersion: kafka.strimzi.io/v1beta1
      fieldsType: FieldsV1
      fieldsV1:
        'f:status':
          .: {}
          'f:conditions': {}
          'f:observedGeneration': {}
      manager: okhttp
      operation: Update
      time: '2020-10-02T09:34:34Z'
  namespace: registry
  labels:
    strimzi.io/cluster: my-cluster
spec:
  config:
    retention.ms: '604800000'
    segment.bytes: '1073741824'
  partitions: 10
  replicas: 3
  topicName: storage-topic
status:
  conditions:
    - lastTransitionTime: '2020-10-02T09:34:34.743Z'
      status: 'True'
      type: Ready
  observedGeneration: 1
