apiVersion: kafka.strimzi.io/v1beta1
kind: Kafka
metadata:
  creationTimestamp: '2020-10-01T18:56:53Z'
  generation: 1
  managedFields:
    - apiVersion: kafka.strimzi.io/v1beta1
      fieldsType: FieldsV1
      fieldsV1:
        'f:spec':
          'f:entityOperator':
            'f:topicOperator':
              'f:topicMetadataMaxAttempts': {}
              'f:zookeeperSessionTimeoutSeconds': {}
            'f:userOperator':
              'f:zookeeperSessionTimeoutSeconds': {}
        'f:status':
          'f:conditions': {}
          'f:listeners': {}
      manager: okhttp
      operation: Update
      time: '2020-10-02T09:34:00Z'
  name: investigation-cluster
  namespace: event-driven-demo
  resourceVersion: '694199'
  selfLink: >-
    /apis/kafka.strimzi.io/v1beta1/namespaces/event-driven-demo/kafkas/investigation-cluster
  uid: af4a5ebe-9d61-4829-8a74-eaba1cdbfa4f
spec:
  entityOperator:
    topicOperator:
      reconciliationIntervalSeconds: 90
    userOperator:
      reconciliationIntervalSeconds: 120
  kafka:
    config:
      log.message.format.version: '2.5'
      offsets.topic.replication.factor: 3
      transaction.state.log.min.isr: 2
      transaction.state.log.replication.factor: 3
    listeners:
      plain:
        authentiation:
          type: scram-sha-512
      tls:
        authentiation:
          type: tls
    replicas: 3
    storage:
      type: ephemeral
    version: 2.5.0
  zookeeper:
    replicas: 3
    storage:
      type: ephemeral
status:
  conditions:
    - lastTransitionTime: '2020-10-02T09:34:00+0000'
      status: 'True'
      type: Ready
  listeners:
    - addresses:
        - host: investigation-cluster-kafka-bootstrap.event-driven-demo.svc
          port: 9092
      bootstrapServers: 'investigation-cluster-kafka-bootstrap.event-driven-demo.svc:9092'
      type: plain
    - addresses:
        - host: investigation-cluster-kafka-bootstrap.event-driven-demo.svc
          port: 9093
      bootstrapServers: 'investigation-cluster-kafka-bootstrap.event-driven-demo.svc:9093'
      certificates:
        - |
          -----BEGIN CERTIFICATE-----
          MIIDLTCCAhWgAwIBAgIJAOyVDRjEeUk9MA0GCSqGSIb3DQEBCwUAMC0xEzARBgNV
          BAoMCmlvLnN0cmltemkxFjAUBgNVBAMMDWNsdXN0ZXItY2EgdjAwHhcNMjAxMDAx
          MTg1NjU0WhcNMjExMDAxMTg1NjU0WjAtMRMwEQYDVQQKDAppby5zdHJpbXppMRYw
          FAYDVQQDDA1jbHVzdGVyLWNhIHYwMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIB
          CgKCAQEAtJDp1GCXMi1xREgwXoCGy7vJe+Tzh1ExnBrCpBPckxdvdTSS2sVTEG5N
          tcATWwMh74rqBRS/BBevQEN0Irjqseg0ys84hpUwmjxRxGzia+kI9t3Sk+Chshiq
          EAYMb5lw5vENPB7VLJ0GqdXvm4b/fU66FkIPAmvoWTV51kReEbW6AA8Sczw5Twq3
          KLgwC+bfOCieImqS+f4tDKSNzTqipLIpVB107yx4uFq4RnjgC/VpukA1TsJUQJNq
          CDNlNHh7jfIRRBgz5yKbRPMSLKHxFr6wNwxXZ3oYKjujzn3X/KMbVpmiQksO4jbk
          5c+B0+o1jCcquFQavQjYp0T9fMUALwIDAQABo1AwTjAdBgNVHQ4EFgQUc9mv1AtG
          D568V0gJxp3hHlTB538wHwYDVR0jBBgwFoAUc9mv1AtGD568V0gJxp3hHlTB538w
          DAYDVR0TBAUwAwEB/zANBgkqhkiG9w0BAQsFAAOCAQEAdYcOewr+PInthCzG4G/9
          ofyvUL+ggHuUbIcg4fvE68GI+AC1xic3xQXK++G0zK+IW97hWAEl/bGChYk45/Qt
          xdCqvOqcux0MJoIE9bNjaDlZy3D/7byKhQcy22+S1AE492ig0+ohDPzi/uxEGSVE
          ketO2vbtBWsfaQ4/19LiyouDo9FmeO+q6XmNB04raKz2Mn2nDpirVwRbdiROzi/V
          9rQbR4MYyJPKE2ogE3T2GXC0i/41KCURtMX1phOcT3HLq1bfiR3SMB9laxu4Vvsb
          exKjDlqzSBFztvzpHjhY+M1JO6/UXQBICP+mq4kWjq6UtFNvV8G/1vOtT4PWVKYj
          fg==
          -----END CERTIFICATE-----
      type: tls
  observedGeneration: 1
