apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus
  namespace: myproject
---

apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: prometheus
rules:
- apiGroups: [""]
  resources:
  - nodes
  - nodes/metrics
  - nodes/proxy
  - services
  - endpoints
  - pods
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources:
  - configmaps
  verbs: ["get"]
- nonResourceURLs: ["/metrics"]
  verbs: ["get"]
---

apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: prometheus
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prometheus
subjects:
- kind: ServiceAccount
  name: prometheus
  namespace: myproject
---

kind: Service
apiVersion: v1
metadata:
  name: prometheus
  labels:
    app: prometheus
  namespace: myproject
spec:
  type: ClusterIP
  ports:
    - port: 80
      name: http
      protocol: TCP
      targetPort: web
  selector:
    prometheus: prometheus
---

apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: prometheus
  labels:
    app: prometheus
  namespace: myproject
spec:
  port:
    targetPort: http
  to:
    kind: Service
    name: prometheus
---

apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus
  labels:
    app: prometheus
  namespace: myproject
spec:
  replicas: 1
  serviceAccountName: prometheus
  enableAdminAPI: true
  storage:
    volumeClaimTemplate:
      spec:
        resources:
          requests:
            storage: 10Gi
  serviceMonitorSelector:
    matchLabels:
      prometheus: prometheus
  podMonitorSelector:
    matchLabels:
      prometheus: prometheus
  additionalScrapeConfigs:
    name: additional-scrape-configs
    key: prometheus-additional.yaml
  alerting:
    alertmanagers:
    - namespace: myproject
      name: alertmanager
      port: http
---

kind: Secret
apiVersion: v1
metadata:
  name: additional-scrape-configs
  labels:
    app: prometheus
  namespace: myproject
type: Opaque
data:
  prometheus-additional.yaml: LSBqb2JfbmFtZTogImt1YmVybmV0ZXMtY2Fkdmlzb3IiCiAgaG9ub3JfbGFiZWxzOiB0cnVlCiAgc2NyYXBlX2ludGVydmFsOiAxMHMKICBzY3JhcGVfdGltZW91dDogMTBzCiAgbWV0cmljc19wYXRoOiAvbWV0cmljcwogIHNjaGVtZTogaHR0cHMKICBrdWJlcm5ldGVzX3NkX2NvbmZpZ3M6CiAgLSByb2xlOiBub2RlCiAgICBuYW1lc3BhY2VzOgogICAgICBuYW1lczogW10KICBiZWFyZXJfdG9rZW5fZmlsZTogL3Zhci9ydW4vc2VjcmV0cy9rdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3Rva2VuCiAgdGxzX2NvbmZpZzoKICAgIGNhX2ZpbGU6IC92YXIvcnVuL3NlY3JldHMva3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9jYS5jcnQKICAgIGluc2VjdXJlX3NraXBfdmVyaWZ5OiB0cnVlCiAgcmVsYWJlbF9jb25maWdzOgogIC0gc2VwYXJhdG9yOiA7CiAgICByZWdleDogX19tZXRhX2t1YmVybmV0ZXNfbm9kZV9sYWJlbF8oLispCiAgICByZXBsYWNlbWVudDogJDEKICAgIGFjdGlvbjogbGFiZWxtYXAKICAtIHNlcGFyYXRvcjogOwogICAgcmVnZXg6ICguKikKICAgIHRhcmdldF9sYWJlbDogX19hZGRyZXNzX18KICAgIHJlcGxhY2VtZW50OiBrdWJlcm5ldGVzLmRlZmF1bHQuc3ZjOjQ0MwogICAgYWN0aW9uOiByZXBsYWNlCiAgLSBzb3VyY2VfbGFiZWxzOiBbX19tZXRhX2t1YmVybmV0ZXNfbm9kZV9uYW1lXQogICAgc2VwYXJhdG9yOiA7CiAgICByZWdleDogKC4rKQogICAgdGFyZ2V0X2xhYmVsOiBfX21ldHJpY3NfcGF0aF9fCiAgICByZXBsYWNlbWVudDogL2FwaS92MS9ub2Rlcy8kezF9L3Byb3h5L21ldHJpY3MvY2Fkdmlzb3IKICAgIGFjdGlvbjogcmVwbGFjZQogIC0gc291cmNlX2xhYmVsczogW19fbWV0YV9rdWJlcm5ldGVzX25vZGVfbmFtZV0KICAgIHNlcGFyYXRvcjogOwogICAgcmVnZXg6ICguKikKICAgIHRhcmdldF9sYWJlbDogbm9kZV9uYW1lCiAgICByZXBsYWNlbWVudDogJDEKICAgIGFjdGlvbjogcmVwbGFjZQogIC0gc291cmNlX2xhYmVsczogW19fbWV0YV9rdWJlcm5ldGVzX25vZGVfYWRkcmVzc19JbnRlcm5hbElQXQogICAgc2VwYXJhdG9yOiA7CiAgICByZWdleDogKC4qKQogICAgdGFyZ2V0X2xhYmVsOiBub2RlX2lwCiAgICByZXBsYWNlbWVudDogJDEKICAgIGFjdGlvbjogcmVwbGFjZQogIG1ldHJpY19yZWxhYmVsX2NvbmZpZ3M6CiAgLSBzb3VyY2VfbGFiZWxzOiBbcG9kX25hbWVdCiAgICBzZXBhcmF0b3I6IDsKICAgIHJlZ2V4OiAoLiopCiAgICB0YXJnZXRfbGFiZWw6IGt1YmVybmV0ZXNfcG9kX25hbWUKICAgIHJlcGxhY2VtZW50OiAkMQogICAgYWN0aW9uOiByZXBsYWNlCiAgLSBzZXBhcmF0b3I6IDsKICAgIHJlZ2V4OiBwb2RfbmFtZQogICAgcmVwbGFjZW1lbnQ6ICQxCiAgICBhY3Rpb246IGxhYmVsZHJvcAogIC0gc291cmNlX2xhYmVsczogW2NvbnRhaW5lcl9uYW1lLCBfX25hbWVfX10KICAgIHNlcGFyYXRvcjogOwogICAgcmVnZXg6IFBPRDtjb250YWluZXJfKG5ldHdvcmspLioKICAgIHRhcmdldF9sYWJlbDogY29udGFpbmVyX25hbWUKICAgIHJlcGxhY2VtZW50OiAkMQogICAgYWN0aW9uOiByZXBsYWNlCiAgLSBzb3VyY2VfbGFiZWxzOiBbY29udGFpbmVyX25hbWVdCiAgICBzZXBhcmF0b3I6IDsKICAgIHJlZ2V4OiBQT0QKICAgIHJlcGxhY2VtZW50OiAkMQogICAgYWN0aW9uOiBkcm9wCiAgLSBzb3VyY2VfbGFiZWxzOiBbY29udGFpbmVyX25hbWVdCiAgICBzZXBhcmF0b3I6IDsKICAgIHJlZ2V4OiBeJAogICAgcmVwbGFjZW1lbnQ6ICQxCiAgICBhY3Rpb246IGRyb3AKICAtIHNvdXJjZV9sYWJlbHM6IFtfX25hbWVfX10KICAgIHNlcGFyYXRvcjogOwogICAgcmVnZXg6IGNvbnRhaW5lcl8obmV0d29ya190Y3BfdXNhZ2VfdG90YWx8dGFza3Nfc3RhdGV8Y3B1X3VzYWdlX3NlY29uZHNfdG90YWx8bWVtb3J5X2ZhaWx1cmVzX3RvdGFsfG5ldHdvcmtfdWRwX3VzYWdlX3RvdGFsKQogICAgcmVwbGFjZW1lbnQ6ICQxCiAgICBhY3Rpb246IGRyb3AKCi0gam9iX25hbWU6IGt1YmVybmV0ZXMtcG9kcwogIGhvbm9yX2xhYmVsczogdHJ1ZQogIHNjcmFwZV9pbnRlcnZhbDogMTBzCiAgc2NyYXBlX3RpbWVvdXQ6IDEwcwogIG1ldHJpY3NfcGF0aDogL21ldHJpY3MKICBzY2hlbWU6IGh0dHAKICBrdWJlcm5ldGVzX3NkX2NvbmZpZ3M6CiAgLSByb2xlOiBwb2QKICAgIG5hbWVzcGFjZXM6CiAgICAgIG5hbWVzOiBbXQogIHJlbGFiZWxfY29uZmlnczoKICAtIHNvdXJjZV9sYWJlbHM6IFtfX21ldGFfa3ViZXJuZXRlc19wb2RfYW5ub3RhdGlvbl9wcm9tZXRoZXVzX2lvX3NjcmFwZV0KICAgIHNlcGFyYXRvcjogOwogICAgcmVnZXg6ICJ0cnVlIgogICAgcmVwbGFjZW1lbnQ6ICQxCiAgICBhY3Rpb246IGtlZXAKICAtIHNvdXJjZV9sYWJlbHM6IFtfX21ldGFfa3ViZXJuZXRlc19wb2RfYW5ub3RhdGlvbl9wcm9tZXRoZXVzX2lvX3BhdGhdCiAgICBzZXBhcmF0b3I6IDsKICAgIHJlZ2V4OiAoLispCiAgICB0YXJnZXRfbGFiZWw6IF9fbWV0cmljc19wYXRoX18KICAgIHJlcGxhY2VtZW50OiAkMQogICAgYWN0aW9uOiByZXBsYWNlCiAgLSBzb3VyY2VfbGFiZWxzOiBbX19tZXRhX2t1YmVybmV0ZXNfcG9kX2Fubm90YXRpb25fcHJvbWV0aGV1c19pb19wb3J0LCBfX21ldGFfa3ViZXJuZXRlc19wb2RfY29udGFpbmVyX3BvcnRfbmFtZV0KICAgIHNlcGFyYXRvcjogOwogICAgcmVnZXg6IF4oLis7LiopfCg7LiptZXRyaWNzKSQKICAgIHJlcGxhY2VtZW50OiAkMQogICAgYWN0aW9uOiBrZWVwCiAgLSBzb3VyY2VfbGFiZWxzOiBbX19hZGRyZXNzX18sIF9fbWV0YV9rdWJlcm5ldGVzX3BvZF9hbm5vdGF0aW9uX3Byb21ldGhldXNfaW9fcG9ydF0KICAgIHNlcGFyYXRvcjogOwogICAgcmVnZXg6ICguKyk6KD86XGQrKTsoXGQrKQogICAgdGFyZ2V0X2xhYmVsOiBfX2FkZHJlc3NfXwogICAgcmVwbGFjZW1lbnQ6ICR7MX06JHsyfQogICAgYWN0aW9uOiByZXBsYWNlCiAgLSBzZXBhcmF0b3I6IDsKICAgIHJlZ2V4OiBfX21ldGFfa3ViZXJuZXRlc19wb2RfbGFiZWxfKC4rKQogICAgcmVwbGFjZW1lbnQ6ICQxCiAgICBhY3Rpb246IGxhYmVsbWFwCiAgLSBzb3VyY2VfbGFiZWxzOiBbX19tZXRhX2t1YmVybmV0ZXNfbmFtZXNwYWNlXQogICAgc2VwYXJhdG9yOiA7CiAgICByZWdleDogKC4qKQogICAgdGFyZ2V0X2xhYmVsOiBuYW1lc3BhY2UKICAgIHJlcGxhY2VtZW50OiAkMQogICAgYWN0aW9uOiByZXBsYWNlCiAgLSBzb3VyY2VfbGFiZWxzOiBbX19tZXRhX2t1YmVybmV0ZXNfcG9kX25hbWVdCiAgICBzZXBhcmF0b3I6IDsKICAgIHJlZ2V4OiAoLiopCiAgICB0YXJnZXRfbGFiZWw6IGt1YmVybmV0ZXNfcG9kX25hbWUKICAgIHJlcGxhY2VtZW50OiAkMQogICAgYWN0aW9uOiByZXBsYWNlCiAgLSBzb3VyY2VfbGFiZWxzOiBbX19tZXRhX2t1YmVybmV0ZXNfcG9kX25vZGVfbmFtZV0KICAgIHNlcGFyYXRvcjogOwogICAgcmVnZXg6ICguKikKICAgIHRhcmdldF9sYWJlbDogbm9kZV9uYW1lCiAgICByZXBsYWNlbWVudDogJDEKICAgIGFjdGlvbjogcmVwbGFjZQogIC0gc291cmNlX2xhYmVsczogW19fbWV0YV9rdWJlcm5ldGVzX3BvZF9ob3N0X2lwXQogICAgc2VwYXJhdG9yOiA7CiAgICByZWdleDogKC4qKQogICAgdGFyZ2V0X2xhYmVsOiBub2RlX2lwCiAgICByZXBsYWNlbWVudDogJDEKICAgIGFjdGlvbjogcmVwbGFjZQotIGpvYl9uYW1lOiBrdWJlcm5ldGVzLW5vZGVzLWt1YmVsZXQKICBzY3JhcGVfaW50ZXJ2YWw6IDEwcwogIHNjcmFwZV90aW1lb3V0OiAxMHMKICBzY2hlbWU6IGh0dHBzCiAga3ViZXJuZXRlc19zZF9jb25maWdzOgogIC0gcm9sZTogbm9kZQogICAgbmFtZXNwYWNlczoKICAgICAgbmFtZXM6IFtdCiAgYmVhcmVyX3Rva2VuX2ZpbGU6IC92YXIvcnVuL3NlY3JldHMva3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC90b2tlbgogIHRsc19jb25maWc6CiAgICBjYV9maWxlOiAvdmFyL3J1bi9zZWNyZXRzL2t1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvY2EuY3J0CiAgICBpbnNlY3VyZV9za2lwX3ZlcmlmeTogdHJ1ZQogIHJlbGFiZWxfY29uZmlnczoKICAtIGFjdGlvbjogbGFiZWxtYXAKICAgIHJlZ2V4OiBfX21ldGFfa3ViZXJuZXRlc19ub2RlX2xhYmVsXyguKykKICAtIHRhcmdldF9sYWJlbDogX19hZGRyZXNzX18KICAgIHJlcGxhY2VtZW50OiBrdWJlcm5ldGVzLmRlZmF1bHQuc3ZjOjQ0MwogIC0gc291cmNlX2xhYmVsczogW19fbWV0YV9rdWJlcm5ldGVzX25vZGVfbmFtZV0KICAgIHJlZ2V4OiAoLispCiAgICB0YXJnZXRfbGFiZWw6IF9fbWV0cmljc19wYXRoX18KICAgIHJlcGxhY2VtZW50OiAvYXBpL3YxL25vZGVzLyR7MX0vcHJveHkvbWV0cmljcwoKLSBqb2JfbmFtZToga3ViZXJuZXRlcy1zZXJ2aWNlcwogIGhvbm9yX2xhYmVsczogdHJ1ZQogIHNjcmFwZV9pbnRlcnZhbDogMTBzCiAgc2NyYXBlX3RpbWVvdXQ6IDEwcwogIG1ldHJpY3NfcGF0aDogL21ldHJpY3MKICBzY2hlbWU6IGh0dHAKICBrdWJlcm5ldGVzX3NkX2NvbmZpZ3M6CiAgLSBhcGlfc2VydmVyOiBudWxsCiAgICByb2xlOiBlbmRwb2ludHMKICAgIG5hbWVzcGFjZXM6CiAgICAgIG5hbWVzOiBbXQogIHJlbGFiZWxfY29uZmlnczoKICAtIHNvdXJjZV9sYWJlbHM6IFtfX21ldGFfa3ViZXJuZXRlc19lbmRwb2ludHNfbmFtZV0KICAgIHNlcGFyYXRvcjogOwogICAgcmVnZXg6IHByb21ldGhldXMtbm9kZS1leHBvcnRlcgogICAgcmVwbGFjZW1lbnQ6ICQxCiAgICBhY3Rpb246IGRyb3AKICAtIHNvdXJjZV9sYWJlbHM6IFtfX21ldGFfa3ViZXJuZXRlc19lbmRwb2ludHNfbmFtZV0KICAgIHNlcGFyYXRvcjogOwogICAgcmVnZXg6IHByb21ldGhldXMta3ViZS1zdGF0ZS1tZXRyaWNzCiAgICByZXBsYWNlbWVudDogJDEKICAgIGFjdGlvbjogZHJvcAogIC0gc291cmNlX2xhYmVsczogW19fbWV0YV9rdWJlcm5ldGVzX3NlcnZpY2VfYW5ub3RhdGlvbl9wcm9tZXRoZXVzX2lvX3NjcmFwZV0KICAgIHNlcGFyYXRvcjogOwogICAgcmVnZXg6ICJ0cnVlIgogICAgcmVwbGFjZW1lbnQ6ICQxCiAgICBhY3Rpb246IGtlZXAKICAtIHNvdXJjZV9sYWJlbHM6IFtfX21ldGFfa3ViZXJuZXRlc19zZXJ2aWNlX2Fubm90YXRpb25fcHJvbWV0aGV1c19pb19zY2hlbWVdCiAgICBzZXBhcmF0b3I6IDsKICAgIHJlZ2V4OiAoaHR0cHM/KQogICAgdGFyZ2V0X2xhYmVsOiBfX3NjaGVtZV9fCiAgICByZXBsYWNlbWVudDogJDEKICAgIGFjdGlvbjogcmVwbGFjZQogIC0gc291cmNlX2xhYmVsczogW19fbWV0YV9rdWJlcm5ldGVzX3NlcnZpY2VfYW5ub3RhdGlvbl9wcm9tZXRoZXVzX2lvX3BhdGhdCiAgICBzZXBhcmF0b3I6IDsKICAgIHJlZ2V4OiAoLispCiAgICB0YXJnZXRfbGFiZWw6IF9fbWV0cmljc19wYXRoX18KICAgIHJlcGxhY2VtZW50OiAkMQogICAgYWN0aW9uOiByZXBsYWNlCiAgLSBzb3VyY2VfbGFiZWxzOiBbX19hZGRyZXNzX18sIF9fbWV0YV9rdWJlcm5ldGVzX3NlcnZpY2VfYW5ub3RhdGlvbl9wcm9tZXRoZXVzX2lvX3BvcnRdCiAgICBzZXBhcmF0b3I6IDsKICAgIHJlZ2V4OiAoLispKD86OlxkKyk7KFxkKykKICAgIHRhcmdldF9sYWJlbDogX19hZGRyZXNzX18KICAgIHJlcGxhY2VtZW50OiAkMTokMgogICAgYWN0aW9uOiByZXBsYWNlCiAgLSBzZXBhcmF0b3I6IDsKICAgIHJlZ2V4OiBfX21ldGFfa3ViZXJuZXRlc19zZXJ2aWNlX2xhYmVsXyguKykKICAgIHJlcGxhY2VtZW50OiAkMQogICAgYWN0aW9uOiBsYWJlbG1hcAogIC0gc291cmNlX2xhYmVsczogW19fbWV0YV9rdWJlcm5ldGVzX25hbWVzcGFjZV0KICAgIHNlcGFyYXRvcjogOwogICAgcmVnZXg6ICguKikKICAgIHRhcmdldF9sYWJlbDogbmFtZXNwYWNlCiAgICByZXBsYWNlbWVudDogJDEKICAgIGFjdGlvbjogcmVwbGFjZQogIC0gc291cmNlX2xhYmVsczogW19fbWV0YV9rdWJlcm5ldGVzX25hbWVzcGFjZV0KICAgIHNlcGFyYXRvcjogOwogICAgcmVnZXg6ICguKikKICAgIHRhcmdldF9sYWJlbDoga3ViZXJuZXRlc19uYW1lc3BhY2UKICAgIHJlcGxhY2VtZW50OiAkMQogICAgYWN0aW9uOiByZXBsYWNlCiAgLSBzb3VyY2VfbGFiZWxzOiBbX19tZXRhX2t1YmVybmV0ZXNfc2VydmljZV9uYW1lXQogICAgc2VwYXJhdG9yOiA7CiAgICByZWdleDogKC4qKQogICAgdGFyZ2V0X2xhYmVsOiBrdWJlcm5ldGVzX25hbWUKICAgIHJlcGxhY2VtZW50OiAkMQogICAgYWN0aW9uOiByZXBsYWNlCiAgLSBzb3VyY2VfbGFiZWxzOiBbX19tZXRhX2t1YmVybmV0ZXNfcG9kX25vZGVfbmFtZV0KICAgIHNlcGFyYXRvcjogOwogICAgcmVnZXg6ICguKikKICAgIHRhcmdldF9sYWJlbDogbm9kZV9uYW1lCiAgICByZXBsYWNlbWVudDogJDEKICAgIGFjdGlvbjogcmVwbGFjZQogIC0gc291cmNlX2xhYmVsczogW19fbWV0YV9rdWJlcm5ldGVzX3BvZF9ob3N0X2lwXQogICAgc2VwYXJhdG9yOiA7CiAgICByZWdleDogKC4qKQogICAgdGFyZ2V0X2xhYmVsOiBub2RlX2lwCiAgICByZXBsYWNlbWVudDogJDEKICAgIGFjdGlvbjogcmVwbGFjZQogIC0gc2VwYXJhdG9yOiA7CiAgICByZWdleDogX19tZXRhX2t1YmVybmV0ZXNfcG9kX2xhYmVsXyguKykKICAgIHJlcGxhY2VtZW50OiAkMQogICAgYWN0aW9uOiBsYWJlbG1hcAogIC0gc291cmNlX2xhYmVsczogW19fbWV0YV9rdWJlcm5ldGVzX3BvZF9uYW1lXQogICAgc2VwYXJhdG9yOiA7CiAgICByZWdleDogKC4qKQogICAgdGFyZ2V0X2xhYmVsOiBrdWJlcm5ldGVzX3BvZF9uYW1lCiAgICByZXBsYWNlbWVudDogJDEKICAgIGFjdGlvbjogcmVwbGFjZQo=
---

apiVersion: monitoring.coreos.com/v1
kind: Alertmanager
metadata:
  name: alertmanager
  labels:
    app: prometheus
  namespace: myproject
spec:
  replicas: 1
---

kind: Service
apiVersion: v1
metadata:
  labels:
    app: prometheus
  name: alertmanager
  namespace: myproject
spec:
  type: ClusterIP
  ports:
    - port: 80
      name: http
      protocol: TCP
      targetPort: web
  selector:
    alertmanager: alertmanager
---

apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: alertmanager
  labels:
    app: prometheus
  namespace: myproject
spec:
  port:
    targetPort: http
  to:
    kind: Service
    name: alertmanager
---

kind: Secret
apiVersion: v1
metadata:
  name: alertmanager-alertmanager
  labels:
    app: prometheus
  namespace: myproject
type: Opaque
data:
  alertmanager.yaml: Z2xvYmFsOgogIHNsYWNrX2FwaV91cmw6IGh0dHBzOi8vaG9va3Muc2xhY2suY29tL3NlcnZpY2VzLzxBUElfS0VZPgpyb3V0ZToKICByZWNlaXZlcjogc2xhY2sKcmVjZWl2ZXJzOgotIG5hbWU6IHNsYWNrCiAgc2xhY2tfY29uZmlnczoKICAtIGNoYW5uZWw6ICIjamFrdWItYWxlcnRzIgogICAgdGl0bGU6ICJ7eyByYW5nZSAuQWxlcnRzIH19e3sgLkFubm90YXRpb25zLnN1bW1hcnkgfX1cbnt7IGVuZCB9fSIKICAgIHRleHQ6ICJ7eyByYW5nZSAuQWxlcnRzIH19e3sgLkFubm90YXRpb25zLmRlc2NyaXB0aW9uIH19XG57eyBlbmQgfX0iCiAgICBzZW5kX3Jlc29sdmVkOiB0cnVlCg==
---

apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: strimzi-cluster-operator-metrics
  labels:
    app: strimzi
    prometheus: prometheus
  namespace: myproject
spec:
  selector:
    matchLabels:
      strimzi.io/kind: cluster-operator
  namespaceSelector:
    matchNames:
      - myproject
  podMetricsEndpoints:
  - path: /metrics
    port: http
---

apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: strimzi-entity-operator-metrics
  labels:
    app: strimzi
    prometheus: prometheus
  namespace: myproject
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: entity-operator
  namespaceSelector:
    matchNames:
      - myproject
  podMetricsEndpoints:
  - path: /metrics
    port: healthcheck