apiVersion: kafka.strimzi.io/v1alpha1
kind: KafkaMirrorMaker2
metadata:
  name: my-mm2-cluster
  namespace: event-driven-demo
spec:
  clusters:
    - alias: operational-cluster
      bootstrapServers: 'operational-cluster-kafka-bootstrap:9092'
    - alias: investigation-cluster
      bootstrapServers: 'investigation-cluster-kafka-bootstrap:9092'
      config:
        config.storage.replication.factor: 1
        offset.storage.replication.factor: 1
        status.storage.replication.factor: 1
  connectCluster: investigation-cluster
  mirrors:
    - checkpointConnector:
        config:
          checkpoints.topic.replication.factor: 1
      groupsPattern: .*
      heartbeatConnector:
        config:
          heartbeats.topic.replication.factor: 1
      sourceCluster: operational-cluster
      sourceConnector:
        config:
          offset-syncs.topic.replication.factor: 1
          replication.factor: 1
          sync.topic.acls.enabled: 'false'
      targetCluster: investigation-cluster
      topicsPattern: transaction-whitelist
  replicas: 1
  version: 2.5.0
